### ISSUE TITLE
Bug: Some pages are cropped if the PDF contains multiple page sizes.

### ISSUE THREAD

**Issue by Muhammad95959** [pwmt/zathura#602]
![2024-06-17_05-54](https://github.com/pwmt/zathura/assets/75130655/31c16378-eff9-47f7-8943-771e4f18c69e)

**Comment by ioannis-vm** [comment]
I'm facing the same issue. This didn't happen in past versions.
```
zathura 0.5.6
girara 0.4.4 (runtime: 0.4.4)
(plugin) ps (0.2.7) (/usr/lib/zathura/libps.so)
(plugin) pdf-mupdf (0.4.3) (/usr/lib/zathura/libpdf-mupdf.so)
```
```
OS: Arch Linux x86_64
Kernel: 6.9.6-arch1-1
```

**Comment by sebastinas** [comment]
Fixed in 9c0017b.

**Comment by Muhammad95959** [comment]
> Fixed in [9c0017b](https://github.com/pwmt/zathura/commit/9c0017b4ddd086a695a8092db6affe06c687d6da).

![image](https://github.com/user-attachments/assets/b0cd15ad-1564-4e51-adf5-e04ad2efb7bb)

the bug is still there in version 0.5.8

**Comment by sebastinas** [comment]
Indeed. This needs still more investigation.

**Comment by doragasu** [comment]
This also happens with rotated pages (I suppose it is the same bug, but not 100% sure). For example on [ESP32-S3 Technical Reference Manual](https://www.espressif.com/sites/default/files/documentation/esp32-s3_technical_reference_manual_en.pdf), pages 478 to 487.

**Comment by vinc17fr** [comment]
Same problem. Here's a simpler testcase with an A5 page followed by an A4 page:  [mediaboxes.pdf](https://github.com/user-attachments/files/16754635/mediaboxes.pdf)

**Comment by yousufinternet** [comment]
Hope more attention is given to this.. Zathura is basically unusable for me as most of the documents I get at work contain multiple page sizes

**Comment by asdfnol** [comment]
yea it makes manga unreadable with the page spreads

**Comment by Muhammad95959** [comment]
For those who are looking for a temporarily solution just use these old versions :-
```
zathura 0.4.9
girara 0.3.7 (runtime: 0.3.7)
(plugin) pdf-poppler (0.3.0) (/usr/lib/zathura/libpdf-poppler.so)
```

**Comment by MightyPlaza** [comment]
seems to be fixed on -git for me (likely from last commit on https://github.com/pwmt/zathura/pull/609)
any chance we can get a new release?

**Comment by sebastinas** [comment]
Fixed in 7fb21f32ba2d94cc3b85c6a67628849ef5b1a422
